sudo: required

services:
  - docker

before_install:
 - docker build -t sample/simple -f Dockerfile.dev .
  

script:
 - docker run sample/simple npm run test -- --coverage

deploy: 
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-2-861206885365"
 bucker_path: "docker"

on:
 branch: master
access_key: $AWS_ACCESS_KEY
secret_access_key:
  secure: "$AWS_SECRET_KEY"